<?php

// database/seeders/UserSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Create SYSTEM account (id = 1)
        DB::table('users')->insert([
            'id' => 1,
            'registration_number' => 'SYSTEM',
            'full_name' => 'System Account',
            'email' => 'system@university.edu.pk',
            'profile_image' => 'profiles/system.png',
            'phone_number' => '+920000000000',
            'birth_date' => '2000-01-01',
            'department' => 'Administration',
            'postal_code' => '25000',
            'address' => 'System Core Internal Server, Peshawar',
            'wallet_balance' => 0.00,
            'pin' => Hash::make('0000'),
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // 2. Create 50+ Dummy Students distributed across different departments
        $students = [
            [
                'registration_number' => 'BF25PwCS1700',
                'full_name' => 'Irfan Ullah Amin',
                'email' => 'irfan.ullah@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcs1700.png',
                'phone_number' => '+923001700123',
                'birth_date' => '2002-04-12',
                'department' => 'Computer Science',
                'postal_code' => '25000',
                'address' => 'Hostel 3, Room 45, University Campus, Peshawar',
                'wallet_balance' => 5000.00,
                'pin' => '1234',
            ],
            [
                'registration_number' => 'BF25PwSE1532',
                'full_name' => 'Syed Ishaq Ahmad shah',
                'email' => 'syed.ishaq@university.edu.pk',
                'profile_image' => 'profiles/bf25pwse1532.png',
                'phone_number' => '+923001532123',
                'birth_date' => '2003-08-22',
                'department' => 'Software Engineering',
                'postal_code' => '25000',
                'address' => 'Hayatabad Phase 4, Street 5, House 12, Peshawar',
                'wallet_balance' => 3000.00,
                'pin' => '1234',
            ],
            [
                'registration_number' => 'BF25PwEE1001',
                'full_name' => 'Ali Raza',
                'email' => 'ali.raza@university.edu.pk',
                'profile_image' => 'profiles/bf25pwee1001.png',
                'phone_number' => '+923001001123',
                'birth_date' => '2002-01-15',
                'department' => 'Electrical Engineering',
                'postal_code' => '25000',
                'address' => 'Sector H-3, Phase 2, Hayatabad, Peshawar',
                'wallet_balance' => 2500.00,
                'pin' => '1111',
            ],
            [
                'registration_number' => 'BF25PwDS1002',
                'full_name' => 'Fatima Khan',
                'email' => 'fatima.khan@university.edu.pk',
                'profile_image' => 'profiles/bf25pwds1002.png',
                'phone_number' => '+923001002123',
                'birth_date' => '2003-05-18',
                'department' => 'Data Science',
                'postal_code' => '25000',
                'address' => 'Gulbahar Colony, House 44, Peshawar',
                'wallet_balance' => 4200.00,
                'pin' => '2222',
            ],
            [
                'registration_number' => 'BF25PwCY1003',
                'full_name' => 'Ahmed Hassan',
                'email' => 'ahmed.hassan@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcy1003.png',
                'phone_number' => '+923001003123',
                'birth_date' => '2001-11-05',
                'department' => 'Cyber Security',
                'postal_code' => '25000',
                'address' => 'University Road, Opposite Town Towers, Peshawar',
                'wallet_balance' => 1800.00,
                'pin' => '3333',
            ],
            [
                'registration_number' => 'BF25PwCE1004',
                'full_name' => 'Sara Bibi',
                'email' => 'sara.bibi@university.edu.pk',
                'profile_image' => 'profiles/bf25pwce1004.png',
                'phone_number' => '+923001004123',
                'birth_date' => '2004-02-28',
                'department' => 'Civil Engineering',
                'postal_code' => '25000',
                'address' => 'Girls Hostel 1, University of Peshawar, Peshawar',
                'wallet_balance' => 6200.00,
                'pin' => '4444',
            ],
            [
                'registration_number' => 'BF25PwME1005',
                'full_name' => 'Usman Khan',
                'email' => 'usman.khan@university.edu.pk',
                'profile_image' => 'profiles/bf25pwme1005.png',
                'phone_number' => '+923001005123',
                'birth_date' => '2002-07-19',
                'department' => 'Mechanical Engineering',
                'postal_code' => '25000',
                'address' => 'Saddar Cantt, Mall Road, Peshawar',
                'wallet_balance' => 3500.00,
                'pin' => '5555',
            ],
            [
                'registration_number' => 'BF25PwBA1006',
                'full_name' => 'Ayesha Malik',
                'email' => 'ayesha.malik@university.edu.pk',
                'profile_image' => 'profiles/bf25pwba1006.png',
                'phone_number' => '+923001006123',
                'birth_date' => '2003-09-14',
                'department' => 'Business Administration',
                'postal_code' => '25000',
                'address' => 'Phase 6, Sector F-1, Hayatabad, Peshawar',
                'wallet_balance' => 2800.00,
                'pin' => '6666',
            ],
            [
                'registration_number' => 'BF25PwCS1007',
                'full_name' => 'Bilal Ahmad',
                'email' => 'bilal.ahmad@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcs1007.png',
                'phone_number' => '+923001007123',
                'birth_date' => '2002-12-25',
                'department' => 'Computer Science',
                'postal_code' => '25000',
                'address' => 'Warsak Road, Near Babu Garhi, Peshawar',
                'wallet_balance' => 4500.00,
                'pin' => '7777',
            ],
            [
                'registration_number' => 'BF25PwSE1008',
                'full_name' => 'Hina Tariq',
                'wallet_balance' => 3900.00,
                'email' => 'hina.tariq@university.edu.pk',
                'profile_image' => 'profiles/bf25pwse1008.png',
                'phone_number' => '+923001008123',
                'birth_date' => '2003-03-30',
                'department' => 'Software Engineering',
                'postal_code' => '25000',
                'address' => 'Regi Model Town, Block C, Peshawar',
                'pin' => '8888',
            ],
            [
                'registration_number' => 'BF25PwEE1009',
                'full_name' => 'Omar Farooq',
                'email' => 'omar.farooq@university.edu.pk',
                'profile_image' => 'profiles/bf25pwee1009.png',
                'phone_number' => '+923001009123',
                'birth_date' => '2001-06-10',
                'department' => 'Electrical Engineering',
                'postal_code' => '25000',
                'address' => 'Charsadda Road, Near Northern Bypass, Peshawar',
                'wallet_balance' => 5100.00,
                'pin' => '9999',
            ],
            [
                'registration_number' => 'BF25PwDS1010',
                'full_name' => 'Zainab Ali',
                'email' => 'zainab.ali@university.edu.pk',
                'profile_image' => 'profiles/bf25pwds1010.png',
                'phone_number' => '+923001010123',
                'birth_date' => '2004-01-01',
                'department' => 'Data Science',
                'postal_code' => '25000',
                'address' => 'Defense Colony, Street 2, Peshawar Cantt',
                'wallet_balance' => 2300.00,
                'pin' => '1010',
            ],
            [
                'registration_number' => 'BF25PwCY1011',
                'full_name' => 'Hamza Ahmed',
                'email' => 'hamza.ahmed@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcy1011.png',
                'phone_number' => '+923001011123',
                'birth_date' => '2002-10-11',
                'department' => 'Cyber Security',
                'postal_code' => '25000',
                'address' => 'Board Bazar, Jamrud Road, Peshawar',
                'wallet_balance' => 3200.00,
                'pin' => '1122',
            ],
            [
                'registration_number' => 'BF25PwCE1012',
                'full_name' => 'Maham Naseer',
                'email' => 'maham.naseer@university.edu.pk',
                'profile_image' => 'profiles/bf25pwce1012.png',
                'phone_number' => '+923001012123',
                'birth_date' => '2003-04-17',
                'department' => 'Civil Engineering',
                'postal_code' => '25000',
                'address' => 'Phase 1, Sector E-3, Hayatabad, Peshawar',
                'wallet_balance' => 4700.00,
                'pin' => '1133',
            ],
            [
                'registration_number' => 'BF25PwME1013',
                'full_name' => 'Shahid Mehmood',
                'email' => 'shahid.mehmood@university.edu.pk',
                'profile_image' => 'profiles/bf25pwme1013.png',
                'phone_number' => '+923001013123',
                'birth_date' => '2001-08-09',
                'department' => 'Mechanical Engineering',
                'postal_code' => '25000',
                'address' => 'G T Road, Hashnagri, Peshawar',
                'wallet_balance' => 1500.00,
                'pin' => '1144',
            ],
            [
                'registration_number' => 'BF25PwBA1014',
                'full_name' => 'Sadia Mirza',
                'email' => 'sadia.mirza@university.edu.pk',
                'profile_image' => 'profiles/bf25pwba1014.png',
                'phone_number' => '+923001014123',
                'birth_date' => '2003-12-03',
                'department' => 'Business Administration',
                'postal_code' => '25000',
                'address' => 'Shami Road, Officers Colony, Peshawar',
                'wallet_balance' => 6800.00,
                'pin' => '1155',
            ],
            [
                'registration_number' => 'BF25PwCS1015',
                'full_name' => 'Imran Ali',
                'email' => 'imran.ali@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcs1015.png',
                'phone_number' => '+923001015123',
                'birth_date' => '2002-05-24',
                'department' => 'Computer Science',
                'postal_code' => '25000',
                'address' => 'Dalazak Road, Near City School, Peshawar',
                'wallet_balance' => 2900.00,
                'pin' => '1166',
            ],
            [
                'registration_number' => 'BF25PwSE1016',
                'full_name' => 'Nadia Javed',
                'email' => 'nadia.javed@university.edu.pk',
                'profile_image' => 'profiles/bf25pwse1016.png',
                'phone_number' => '+923001016123',
                'birth_date' => '2003-07-13',
                'department' => 'Software Engineering',
                'postal_code' => '25000',
                'address' => 'Hostel 2, Room 12, University Campus, Peshawar',
                'wallet_balance' => 4100.00,
                'pin' => '1177',
            ],
            [
                'registration_number' => 'BF25PwEE1017',
                'full_name' => 'Farhan Akhtar',
                'email' => 'farhan.akhtar@university.edu.pk',
                'profile_image' => 'profiles/bf25pwee1017.png',
                'phone_number' => '+923001017123',
                'birth_date' => '2002-03-19',
                'department' => 'Electrical Engineering',
                'postal_code' => '25000',
                'address' => 'Tehkal Payan, Jamrud Road, Peshawar',
                'wallet_balance' => 5300.00,
                'pin' => '1188',
            ],
            [
                'registration_number' => 'BF25PwDS1018',
                'full_name' => 'Sumaira Tariq',
                'email' => 'sumaira.tariq@university.edu.pk',
                'profile_image' => 'profiles/bf25pwds1018.png',
                'phone_number' => '+923001018123',
                'birth_date' => '2004-06-21',
                'department' => 'Data Science',
                'postal_code' => '25000',
                'address' => 'Khyber Colony No 2, University Road, Peshawar',
                'wallet_balance' => 2200.00,
                'pin' => '1199',
            ],
            [
                'registration_number' => 'BF25PwCY1019',
                'full_name' => 'Noman Khalid',
                'email' => 'noman.khalid@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcy1019.png',
                'phone_number' => '+923001019123',
                'birth_date' => '2002-09-02',
                'department' => 'Cyber Security',
                'postal_code' => '25000',
                'address' => 'Phase 4, Sector M, Hayatabad, Peshawar',
                'wallet_balance' => 3800.00,
                'pin' => '1200',
            ],
            [
                'registration_number' => 'BF25PwCE1020',
                'full_name' => 'Rabia Arshad',
                'email' => 'rabia.arshad@university.edu.pk',
                'profile_image' => 'profiles/bf25pwce1020.png',
                'phone_number' => '+923001020123',
                'birth_date' => '2003-11-11',
                'department' => 'Civil Engineering',
                'postal_code' => '25000',
                'address' => 'Palosi Road, Near Agricultural University, Peshawar',
                'wallet_balance' => 4400.00,
                'pin' => '1211',
            ],
            [
                'registration_number' => 'BF25PwME1021',
                'full_name' => 'Hassan Raza',
                'email' => 'hassan.raza@university.edu.pk',
                'profile_image' => 'profiles/bf25pwme1021.png',
                'phone_number' => '+923001021123',
                'birth_date' => '2002-02-14',
                'department' => 'Mechanical Engineering',
                'postal_code' => '25000',
                'address' => 'Phase 5, Street 9, House 21, Hayatabad, Peshawar',
                'wallet_balance' => 5600.00,
                'pin' => '1222',
            ],
            [
                'registration_number' => 'BF25PwBA1022',
                'full_name' => 'Mariam Khalid',
                'email' => 'mariam.khalid@university.edu.pk',
                'profile_image' => 'profiles/bf25pwba1022.png',
                'phone_number' => '+923001022123',
                'birth_date' => '2003-05-25',
                'department' => 'Business Administration',
                'postal_code' => '25000',
                'address' => 'Canal Bank Road, Warsak Road, Peshawar',
                'wallet_balance' => 1900.00,
                'pin' => '1233',
            ],
            [
                'registration_number' => 'BF25PwCS1023',
                'full_name' => 'Saad Ullah',
                'email' => 'saad.ullah@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcs1023.png',
                'phone_number' => '+923001023123',
                'birth_date' => '2001-07-07',
                'department' => 'Computer Science',
                'postal_code' => '25000',
                'address' => 'Asiatic Colony, Kohat Road, Peshawar',
                'wallet_balance' => 7200.00,
                'pin' => '1244',
            ],
            [
                'registration_number' => 'BF25PwSE1024',
                'full_name' => 'Anum Shahzad',
                'email' => 'anum.shahzad@university.edu.pk',
                'profile_image' => 'profiles/bf25pwse1024.png',
                'phone_number' => '+923001024123',
                'birth_date' => '2004-03-12',
                'department' => 'Software Engineering',
                'postal_code' => '25000',
                'address' => 'Wazir Bagh, Kakshaal, Peshawar City',
                'wallet_balance' => 3100.00,
                'pin' => '1255',
            ],
            [
                'registration_number' => 'BF25PwEE1025',
                'full_name' => 'Waqas Ahmed',
                'email' => 'waqas.ahmed@university.edu.pk',
                'profile_image' => 'profiles/bf25pwee1025.png',
                'phone_number' => '+923001025123',
                'birth_date' => '2002-08-30',
                'department' => 'Electrical Engineering',
                'postal_code' => '25000',
                'address' => 'Phase 3, Chowk Nasir, Hayatabad, Peshawar',
                'wallet_balance' => 2700.00,
                'pin' => '1266',
            ],
            [
                'registration_number' => 'BF25PwDS1026',
                'full_name' => 'Laiba Tariq',
                'email' => 'laiba.tariq@university.edu.pk',
                'profile_image' => 'profiles/bf25pwds1026.png',
                'phone_number' => '+923001026123',
                'birth_date' => '2003-10-04',
                'department' => 'Data Science',
                'postal_code' => '25000',
                'address' => 'Ring Road, Near Achini Chowk, Peshawar',
                'wallet_balance' => 4900.00,
                'pin' => '1277',
            ],
            [
                'registration_number' => 'BF25PwCY1027',
                'full_name' => 'Muzamil Hussain',
                'email' => 'muzamil.hussain@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcy1027.png',
                'phone_number' => '+923001027123',
                'birth_date' => '2001-04-20',
                'department' => 'Cyber Security',
                'postal_code' => '25000',
                'address' => 'Landi Arbab, Ring Road, Peshawar',
                'wallet_balance' => 3400.00,
                'pin' => '1288',
            ],
            [
                'registration_number' => 'BF25PwCE1028',
                'full_name' => 'Eman Fatima',
                'email' => 'eman.fatima@university.edu.pk',
                'profile_image' => 'profiles/bf25pwce1028.png',
                'phone_number' => '+923001028123',
                'birth_date' => '2004-05-14',
                'department' => 'Civil Engineering',
                'postal_code' => '25000',
                'address' => 'Gulberg Colony, House 12-B, Peshawar Cantt',
                'wallet_balance' => 6000.00,
                'pin' => '1299',
            ],
            [
                'registration_number' => 'BF25PwME1029',
                'full_name' => 'Rizwan Ali',
                'email' => 'rizwan.ali@university.edu.pk',
                'profile_image' => 'profiles/bf25pwme1029.png',
                'phone_number' => '+923001029123',
                'birth_date' => '2002-11-09',
                'department' => 'Mechanical Engineering',
                'postal_code' => '25000',
                'address' => 'Peshawar City, Interior walled city, Lahori Gate',
                'wallet_balance' => 2100.00,
                'pin' => '1300',
            ],
            [
                'registration_number' => 'BF25PwBA1030',
                'full_name' => 'Hira Naeem',
                'email' => 'hira.naeem@university.edu.pk',
                'profile_image' => 'profiles/bf25pwba1030.png',
                'phone_number' => '+923001030123',
                'birth_date' => '2003-01-31',
                'department' => 'Business Administration',
                'postal_code' => '25000',
                'address' => 'Phase 7, Sector H, Hayatabad, Peshawar',
                'wallet_balance' => 3700.00,
                'pin' => '1311',
            ],
            [
                'registration_number' => 'BF25PwCS1031',
                'full_name' => 'Shayan Khan',
                'email' => 'shayan.khan@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcs1031.png',
                'phone_number' => '+923001031123',
                'birth_date' => '2002-06-18',
                'department' => 'Computer Science',
                'postal_code' => '25000',
                'address' => 'Tehkal Bala, Jamrud Road, Peshawar',
                'wallet_balance' => 4800.00,
                'pin' => '1322',
            ],
            [
                'registration_number' => 'BF25PwSE1032',
                'full_name' => 'Iqra Aslam',
                'email' => 'iqra.aslam@university.edu.pk',
                'profile_image' => 'profiles/bf25pwse1032.png',
                'phone_number' => '+923001032123',
                'birth_date' => '2003-09-09',
                'department' => 'Software Engineering',
                'postal_code' => '25000',
                'address' => 'Faizabad Colony, Charsadda Road, Peshawar',
                'wallet_balance' => 2600.00,
                'pin' => '1333',
            ],
            [
                'registration_number' => 'BF25PwEE1033',
                'full_name' => 'Danish Ali',
                'email' => 'danish.ali@university.edu.pk',
                'profile_image' => 'profiles/bf25pwee1033.png',
                'phone_number' => '+923001033123',
                'birth_date' => '2002-12-12',
                'department' => 'Electrical Engineering',
                'postal_code' => '25000',
                'address' => 'Saddar, Arbab Road, Peshawar Cantt',
                'wallet_balance' => 4300.00,
                'pin' => '1344',
            ],
            [
                'registration_number' => 'BF25PwDS1034',
                'full_name' => 'Sana Khalid',
                'email' => 'sana.khalid@university.edu.pk',
                'profile_image' => 'profiles/bf25pwds1034.png',
                'phone_number' => '+923001034123',
                'birth_date' => '2003-04-05',
                'department' => 'Data Science',
                'postal_code' => '25000',
                'address' => 'Defense Colony, Street 5, Peshawar Cantt',
                'wallet_balance' => 5500.00,
                'pin' => '1355',
            ],
            [
                'registration_number' => 'BF25PwCY1035',
                'full_name' => 'Owais Ahmed',
                'email' => 'owais.ahmed@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcy1035.png',
                'phone_number' => '+923001035123',
                'birth_date' => '2001-05-17',
                'department' => 'Cyber Security',
                'postal_code' => '25000',
                'address' => 'Bana Mari, Kohat Road, Peshawar City',
                'wallet_balance' => 1700.00,
                'pin' => '1366',
            ],
            [
                'registration_number' => 'BF25PwCE1036',
                'full_name' => 'Areeba Khan',
                'email' => 'areeba.khan@university.edu.pk',
                'profile_image' => 'profiles/bf25pwce1036.png',
                'phone_number' => '+923001036123',
                'birth_date' => '2004-08-24',
                'department' => 'Civil Engineering',
                'postal_code' => '25000',
                'address' => 'Phase 2, Sector J-1, Hayatabad, Peshawar',
                'wallet_balance' => 6400.00,
                'pin' => '1377',
            ],
            [
                'registration_number' => 'BF25PwME1037',
                'full_name' => 'Fahad Malik',
                'email' => 'fahad.malik@university.edu.pk',
                'profile_image' => 'profiles/bf25pwme1037.png',
                'phone_number' => '+923001037123',
                'birth_date' => '2002-03-01',
                'department' => 'Mechanical Engineering',
                'postal_code' => '25000',
                'address' => 'Khyber Medical College Colony, Peshawar',
                'wallet_balance' => 3000.00,
                'pin' => '1388',
            ],
            [
                'registration_number' => 'BF25PwBA1038',
                'full_name' => 'Zara Ahmed',
                'email' => 'zara.ahmed@university.edu.pk',
                'profile_image' => 'profiles/bf25pwba1038.png',
                'phone_number' => '+923001038123',
                'birth_date' => '2003-07-29',
                'department' => 'Business Administration',
                'postal_code' => '25000',
                'address' => 'Regi Model Town, Zone A, Peshawar',
                'wallet_balance' => 4600.00,
                'pin' => '1399',
            ],
            [
                'registration_number' => 'BF25PwCS1039',
                'full_name' => 'Nabeel Khan',
                'email' => 'nabeel.khan@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcs1039.png',
                'phone_number' => '+923001039123',
                'birth_date' => '2001-10-14',
                'department' => 'Computer Science',
                'postal_code' => '25000',
                'address' => 'Nishtarabad, G T Road, Peshawar City',
                'wallet_balance' => 5200.00,
                'pin' => '1400',
            ],
            [
                'registration_number' => 'BF25PwSE1040',
                'full_name' => 'Kinza Ali',
                'email' => 'kinza.ali@university.edu.pk',
                'profile_image' => 'profiles/bf25pwse1040.png',
                'phone_number' => '+923001040123',
                'birth_date' => '2004-02-10',
                'department' => 'Software Engineering',
                'postal_code' => '25000',
                'address' => 'Canal Town, Near University Road, Peshawar',
                'wallet_balance' => 2400.00,
                'pin' => '1411',
            ],
            [
                'registration_number' => 'BF25PwEE1041',
                'full_name' => 'Shahrukh Riaz',
                'email' => 'shahrukh.riaz@university.edu.pk',
                'profile_image' => 'profiles/bf25pwee1041.png',
                'phone_number' => '+923001041123',
                'birth_date' => '2002-01-20',
                'department' => 'Electrical Engineering',
                'postal_code' => '25000',
                'address' => 'Phase 4, Sector N-2, Hayatabad, Peshawar',
                'wallet_balance' => 4000.00,
                'pin' => '1422',
            ],
            [
                'registration_number' => 'BF25PwDS1042',
                'full_name' => 'Fariha Anwar',
                'email' => 'fariha.anwar@university.edu.pk',
                'profile_image' => 'profiles/bf25pwds1042.png',
                'phone_number' => '+923001042123',
                'birth_date' => '2003-06-06',
                'department' => 'Data Science',
                'postal_code' => '25000',
                'address' => 'Gulbahar No. 3, Street 2, Peshawar',
                'wallet_balance' => 5800.00,
                'pin' => '1433',
            ],
            [
                'registration_number' => 'BF25PwCY1043',
                'full_name' => 'Haris Ali',
                'email' => 'haris.ali@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcy1043.png',
                'phone_number' => '+923001043123',
                'birth_date' => '2002-11-30',
                'department' => 'Cyber Security',
                'postal_code' => '25000',
                'address' => 'Warsak Road, Near Mathra, Peshawar',
                'wallet_balance' => 1600.00,
                'pin' => '1444',
            ],
            [
                'registration_number' => 'BF25PwCE1044',
                'full_name' => 'Mehak Akhtar',
                'email' => 'mehak.akhtar@university.edu.pk',
                'profile_image' => 'profiles/bf25pwce1044.png',
                'phone_number' => '+923001044123',
                'birth_date' => '2003-08-16',
                'department' => 'Civil Engineering',
                'postal_code' => '25000',
                'address' => 'Warsak Road, Babu Ghari, Peshawar',
                'wallet_balance' => 7000.00,
                'pin' => '1455',
            ],
            [
                'registration_number' => 'BF25PwME1045',
                'full_name' => 'Taimoor Shah',
                'email' => 'taimoor.shah@university.edu.pk',
                'profile_image' => 'profiles/bf25pwme1045.png',
                'phone_number' => '+923001045123',
                'birth_date' => '2002-05-11',
                'department' => 'Mechanical Engineering',
                'postal_code' => '25000',
                'address' => 'Rahatabad, Near Academy Town, Peshawar',
                'wallet_balance' => 3300.00,
                'pin' => '1466',
            ],
            [
                'registration_number' => 'BF25PwBA1046',
                'full_name' => 'Aiman Malik',
                'email' => 'aiman.malik@university.edu.pk',
                'profile_image' => 'profiles/bf25pwba1046.png',
                'phone_number' => '+923001046123',
                'birth_date' => '2003-03-24',
                'department' => 'Business Administration',
                'postal_code' => '25000',
                'address' => 'Phase 6, Sector C-3, Hayatabad, Peshawar',
                'wallet_balance' => 5000.00,
                'pin' => '1477',
            ],
            [
                'registration_number' => 'BF25PwCS1047',
                'full_name' => 'Rohan Tariq',
                'email' => 'rohan.tariq@university.edu.pk',
                'profile_image' => 'profiles/bf25pwcs1047.png',
                'phone_number' => '+923001047123',
                'birth_date' => '2002-09-12',
                'department' => 'Computer Science',
                'postal_code' => '25000',
                'address' => 'Charkha Khel, Landi Arbab, Peshawar',
                'wallet_balance' => 2800.00,
                'pin' => '1488',
            ],
            [
                'registration_number' => 'BF25PwSE1048',
                'full_name' => 'Aleena Fatima',
                'email' => 'aleena.fatima@university.edu.pk',
                'profile_image' => 'profiles/bf25pwse1048.png',
                'phone_number' => '+923001048123',
                'birth_date' => '2004-01-29',
                'department' => 'Software Engineering',
                'postal_code' => '25000',
                'address' => 'University Town, Park Road, Peshawar',
                'wallet_balance' => 3900.00,
                'pin' => '1499',
            ],
            [
                'registration_number' => 'BF25PwEE1049',
                'full_name' => 'Salman Ali',
                'email' => 'salman.ali@university.edu.pk',
                'profile_image' => 'profiles/bf25pwee1049.png',
                'phone_number' => '+923001049123',
                'birth_date' => '2002-07-03',
                'department' => 'Electrical Engineering',
                'postal_code' => '25000',
                'address' => 'Haji Camp, G T Road, Peshawar City',
                'wallet_balance' => 4500.00,
                'pin' => '1500',
            ],
            [
                'registration_number' => 'BF25PwDS1050',
                'full_name' => 'Uroosa Khan',
                'email' => 'uroosa.khan@university.edu.pk',
                'profile_image' => 'profiles/bf25pwds1050.png',
                'phone_number' => '+923001050123',
                'birth_date' => '2003-12-20',
                'department' => 'Data Science',
                'postal_code' => '25000',
                'address' => 'Phase 1, Sector F-4, Hayatabad, Peshawar',
                'wallet_balance' => 6100.00,
                'pin' => '1511',
            ],
        ];

        // Insert all students cleanly without generating any NULL fields
        foreach ($students as $student) {
            DB::table('users')->insert([
                'registration_number' => $student['registration_number'],
                'full_name' => $student['full_name'],
                'email' => $student['email'],
                'profile_image' => $student['profile_image'],
                'phone_number' => $student['phone_number'],
                'birth_date' => $student['birth_date'],
                'department' => $student['department'],
                'postal_code' => $student['postal_code'],
                'address' => $student['address'],
                'wallet_balance' => $student['wallet_balance'],
                'pin' => Hash::make($student['pin']),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}